### ISSUE TITLE
Green Flashlight for active tcs

### ISSUE THREAD

**Issue by drjakob** [roschaefer/story.board#374]
As reporter
I want to see a "green flashlight" in text component list marking active tcs
in order to better debug the live text.

**Comment by sebroeder** [comment]
Question related to the logic of `TextComponent#active?`, not the visualization in the UI: A text component is considered active, when it does not have any triggers attached to it ([Implementation]( https://github.com/roschaefer/story.board/blob/09f4d548b8325195b0501f52b609679ee4942135/app/models/text_component.rb#L22-L24), [Spec](https://github.com/roschaefer/story.board/blob/09f4d548b8325195b0501f52b609679ee4942135/spec/models/text_component_spec.rb#L48-L52)).

Is this what we want? It seems a little counter-intuitive to me, but this could of cause just be a misunderstanding on my side.

**Comment by drjakob** [comment]
No, a text component is considered active when its selectet to be (potentially) used in the current sensorstory. 
1. The connected trigger is active 
2. Time span of tc is true 
So the function should have debugging purposes: As an editor I read my sensorstory and want to debug the used tcs.)

**Comment by sebroeder** [comment]
What I wanted to say is that in the current implementation in production (see links in the original comment), a text component is **active** when it does not have any triggers attached.

You can try this yourself in the `bin/rails console`:

```
irb(main):001:0> t = TextComponent.new
=> #<TextComponent id: nil, heading: nil, introduction: nil, main_part: nil, closing: nil, from_day: nil, to_day: nil, report_id: nil, topic_id: nil, assignee_id: nil, publication_status: "draft", created_at: nil, updated_at: nil, notes: nil>
irb(main):002:0> t.triggers
=> #<ActiveRecord::Associations::CollectionProxy []>
irb(main):003:0> t.active?
=> true
```

Would you want it to be **inactive** when it does not have any triggers attached instead? Than we have to change the current implementation and maybe document the desired behavior in a Cucumber feature instead of just the model spec.

Again, this is technically not related to the visualization of the active/inactive status that is the scope of this issue, but a question/surprise that came up when I read the implementation of `TextComponent#active?` in the model.

**Comment by roschaefer** [comment]
It's intended that a text component is active if it has no triggers. E.g. there is a condition on the text component itself, a start and end day. If we would change the behaviour to force text components to have at least one active trigger, we would have to catch this situation.

**Comment by sebroeder** [comment]
Back to the UI: should the icon indicating the active/inactive status go in front of the name of the trigger or in front of the name of each text component?

**Comment by drjakob** [comment]
In front of each tc. Important: There could be more tcs for each trigger, but only one could be active.

**Comment by sebroeder** [comment]
> As reporter
I want to see a "green flashlight" in text component list marking active tcs
in order to better debug the live text.

Can you give an example what "better debug the live text" means from the point of view of a reporter? Are they actually using this phrase or is this more like the language we as developers would use, that sneaked into the story?

You only describe how an **active** text component should be marked. What should an **inactive** text component look like?
