### ISSUE TITLE
Text components: Priorities

### ISSUE THREAD

**Issue by drjakob** [roschaefer/story.board#61]
As a journalist
I want to store priorities for text components
So the sensor.bot can make a selection if not all text components fit into a report

**Comment by roschaefer** [comment]
As a journalist I
want to write the sensor-live-report in fields 
because it avoids, that I forgot some conditions.

Heading (ok)
Introduction (ok)
Main part (ok)
!+ menu button to insert value at cursor position as "{value}" [as solved at ifttt]
Closing (ok)
Conditions 
!+ Priority as Combo box (low, medium, high), default should be medium 
– Sensors (ok)
!+ – should show unit of Sensor-Data
!+ virtual Sensors for data received from other software like milkvolume and feeding-time
!+– Events: gekalbt (default: true), trächtig (default: false)  [> need event-creation-mechanism]
!+ – optional Timespan (from to)
+ author of text component, default: Jakob
+ description/notes/explanation [for special implementation or bugs]

**Comment by roschaefer** [comment]
@drjakob we have to talk about the rest of the requirements. I don't see the urgent need or the problem for some of them. What is the purpose to know the author of a text component, to have a description? The [units for the sensor types](https://github.com/roschaefer/story.board/blob/master/db/seeds.rb) don't yield a lot of information to the user at the moment. Why do we need a special event "calved"? Can't this be accomplished by a virtual sensor "Calvings"? By the way, we already have virtual sensors and there is no difference to real sensors in the database.

**Comment by drjakob** [comment]
@ok, lets discuss this.
