### ISSUE TITLE
Add priorities

### ISSUE THREAD

**Issue by drjakob** [roschaefer/story.board#642]
As an editor I need more priorities in order to better adjust to breaking news situations like calving ;)
We just have five priorities. Would be great to get two more:
very low, low, medium, high, NEW: very high, urgent, "NEW Always on top"

**Comment by matthib** [comment]
@drjakob It is definately possible to add new priorities, but adding the "very high" priority could become a problem because of the existing data. The priorities are all assigned to integer values and if I add "very high" in between high and urgent, it would take over the integer value of urgent and all triggers that are set to urgent right now, will then be set to very high. 
Now I could of course write a rake tasks, that changes all priorities to match the urgent integer value again, but I would not like to play around with the database values so much so close to the start of the project. So I could give it a try if this is important or just leave it as it is.
By the way: What if there are two triggers with the "always on top" priority assigned? You cannot display both on top ;)

**Comment by drjakob** [comment]
I see. Its more important to have two new priorities. then add "totally boring" (0) and "always on top". Its relatively clear that only one tc can be on top, so I think there si not much conflict. It should  be used rare and exklusive.
